### ISSUE TITLE
[Request] Addon widget sort by last used

### ISSUE THREAD

**Issue by queeup** [osmc/skin.osmc#125] opened 2019-10-30 23:41 UTC
Please make Addon widget sort by last used. It's very good to have last used apps sorted on the addon widget. Making it with overrides.xml?

**Comment by Ch1llb0** [comment] 2019-10-31 10:05
I'll look into this. There're other skins that offer general widget sort options. Maybe that's something we can add as well. Just not sure about the exact approach other skins are using.

Thanks for the requests and the idea to look into this 👍 Will keep you posted here.

**Comment by Ch1llb0** [comment] 2019-11-01 00:01
Done 👍 With the update following the tonight's one, you'll be able to adjust the sort method and order of widgets. The default program widget will stay the way it is now, but you can adjust it to your liking via the home menu customization dialog of our skin setting...

The new sort options:
![screenshot005](https://user-images.githubusercontent.com/36623079/67993776-a521af00-fc42-11e9-9871-9d7e650f22ca.png)
The sort method you requested for programs/add-ons:
![screenshot006](https://user-images.githubusercontent.com/36623079/67993779-a7840900-fc42-11e9-83bd-7244cafc5d71.png)

I hope, this is what you were looking for.

**Comment by queeup** [comment] 2019-11-01 10:09
It's more than what I am looking for. I am sure many people will be happy about this addition. Thank you.

**Comment by Ch1llb0** [comment] 2019-11-01 10:13
Glad to hear that! Will close this issue... Keep your eyes peeled for the next update. The changes will be available in our starving repo some time next week already.

**Closed by Ch1llb0** 2019-11-01 10:13 UTC

**Comment by queeup** [comment] 2019-11-11 08:53
Hey @Ch1llb0, I tested it. Works great except video addons not have `lastused` option somehow. It shows `lastplayed` sort by option instead `lastused`. Programs works as expected. Can you check it pls?

Reproduce:
 - add widget from Videos > Video addons
 - try to sort by `lastused`

**Comment by Ch1llb0** [comment] 2019-11-11 11:06
The issue is that the `Video add-ons` under the `Video` section is handled as a video library item and therefore the sort option you're looking for is not offered for the widget - this part is controlled by the skinshortcuts script itself and is not something I can control.
I'll fix the issue by adding the `Video add-ons` to the `Add-ons` section a second time. There I can force it to be treated as a program widget offering the sort methods for add-ons... Will push this later today 👍
